//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoChange.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bVFP_DBASE {
            get {
                return ((bool)(this["bVFP_DBASE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\tofind")]
        public string Archive_folder {
            get {
                return ((string)(this["Archive_folder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\pr-server-new\\Инф_обмен\\запрос\\sber")]
        public string Sber_path {
            get {
                return ((string)(this["Sber_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\archive\\\\sber")]
        public string Archive_sber_path {
            get {
                return ((string)(this["Archive_sber_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\archive\\\\cred_org")]
        public string Archive_credorg_path {
            get {
                return ((string)(this["Archive_credorg_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\archive\\\\ktfoms")]
        public string Archive_ktfoms_path {
            get {
                return ((string)(this["Archive_ktfoms_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool readFromCopy {
            get {
                return ((bool)(this["readFromCopy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\archive\\\\pens")]
        public string Archive_pens_path {
            get {
                return ((string)(this["Archive_pens_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\archive\\\\potd")]
        public string Archive_potd_path {
            get {
                return ((string)(this["Archive_potd_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bDateFolderAdd {
            get {
                return ((bool)(this["bDateFolderAdd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8628")]
        public string SberFilial_num {
            get {
                return ((string)(this["SberFilial_num"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\krc")]
        public string Krc_path {
            get {
                return ((string)(this["Krc_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\archive\\\\krc")]
        public string Archive_krc_path {
            get {
                return ((string)(this["Archive_krc_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=LCPI.IBProvider.3;Data Source=firebird;Persist Security Info=True;Passwo" +
            "rd=masterkey;User ID=SYSDBA;Location=firebird:86_21;dbclient_library=C:\\Program " +
            "Files\\Firebird\\Firebird_2_1\\bin\\fbclient.dll;ctype=win1251")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=LCPI.IBProvider.3;Data Source=firebird;Persist Security Info=True;Passwo" +
            "rd=masterkey;User ID=SYSDBA;Location=firebird:86_21;dbclient_library=C:\\Program " +
            "Files\\Firebird\\Firebird_2_1\\bin\\fbclient.dll;ctype=win1251")]
        public string ConnectionString2 {
            get {
                return ((string)(this["ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=LCPI.IBProvider.3;Data Source=vm-rdb/3051;Persist Security Info=True;Pas" +
            "sword=masterkey;User ID=SYSDBA;Location=vm-rdb/3051:ncore-fssp-petr3;dbclient_li" +
            "brary=C:\\Program Files\\Red Soft Corporation\\Red Database\\bin\\fbclient.dll;ctype=" +
            "win1251")]
        public string ConnectionStringRDB {
            get {
                return ((string)(this["ConnectionStringRDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\cred_org")]
        public string Cred_org_path {
            get {
                return ((string)(this["Cred_org_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          86200999999006, 86200999999007, 86200999999008, 86200999999009, 86200" +
            "999999010, 86200999999011, 86200999999012, 86200999999013\r\n        ")]
        public string Legal_list {
            get {
                return ((string)(this["Legal_list"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\ktfoms")]
        public string Ktfoms_path {
            get {
                return ((string)(this["Ktfoms_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86200999999004")]
        public string Ktfoms_id {
            get {
                return ((string)(this["Ktfoms_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\pens")]
        public string Pens_path {
            get {
                return ((string)(this["Pens_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86200999999002")]
        public string Pens_id {
            get {
                return ((string)(this["Pens_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86200999999003")]
        public string Potd_id {
            get {
                return ((string)(this["Potd_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\basebank\\\\potd")]
        public string Potd_path {
            get {
                return ((string)(this["Potd_path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86200999999014")]
        public string Krc_id {
            get {
                return ((string)(this["Krc_id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=LCPI.IBProvider.3;Data Source=fb-petr2.petr2.karelia.ssp;Persist Securit" +
            "y Info=True;Password=masterkey;User ID=SYSDBA;Location=fb-petr2.petr2.karelia.ss" +
            "p:2010;dbclient_library=C:\\Program Files\\Firebird\\Firebird_2_1\\bin\\fbclient.dll;" +
            "ctype=win1251")]
        public string ConnectionStringGIBDD {
            get {
                return ((string)(this["ConnectionStringGIBDD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86200999999015")]
        public string Mvd_id {
            get {
                return ((string)(this["Mvd_id"]));
            }
        }
    }
}
